apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idsm-debugger-ingress-test6
  namespace: sparql
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "21600"
    nginx.ingress.kubernetes.io/eventsource: "true"
spec:
  rules:
    - host: "idsm-debugger-test6.dyn.cloud.e-infra.cz"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: idsm-debugger
                port:
                  number: 80
