#### BULK QUERY: https://sparql.uniprot.org #####

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX sachem: <http://bioinfo.uochb.cas.cz/rdf/v1.0/sachem#>
PREFIX endpoint: <https://idsm.elixir-czech.cz/sparql/endpoint/>

SELECT ?COMPOUND ?UNIPROT ?ORGANISM_NAME WHERE
{
    {
      SELECT ?UNIPROT ?ORGANISM WHERE
      {
        ?UNIPROT uniprot:organism ?ORGANISM.
      } LIMIT 5
    }

    SERVICE endpoint:idsm {
      SERVICE endpoint:chembl {
        SERVICE endpoint:chembl {
          ?COMPOUND sachem:substructureSearch [
              sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
        }
        ?COMPOUND sachem:substructureSearch [
            sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
      }

    ?ACTIVITY rdf:type chembl:Activity;
      chembl:hasMolecule ?COMPOUND;
      chembl:hasAssay ?ASSAY.
    ?ASSAY chembl:hasTarget ?TARGET.
    ?TARGET chembl:hasTargetComponent ?COMPONENT.
    ?COMPONENT chembl:targetCmptXref ?UNIPROT.
    ?UNIPROT rdf:type chembl:UniprotRef.
  }

  ?UNIPROT uniprot:organism ?ORGANISM.
  ?ORGANISM uniprot:scientificName ?ORGANISM_NAME.
}

-------------------------------------------------------------------

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX sachem: <http://bioinfo.uochb.cas.cz/rdf/v1.0/sachem#>
PREFIX endpoint: <https://idsm.elixir-czech.cz/sparql/endpoint/>

SELECT ?COMPOUND ?UNIPROT ?ORGANISM_NAME WHERE
{
  {
    SELECT ?UNIPROT ?ORGANISM WHERE
    {
      ?UNIPROT uniprot:organism ?ORGANISM.
    } LIMIT 10
  }

    SERVICE <https://idsm.elixir-czech.cz/sparql/endpoint/idsm> {
      SERVICE <https://idsm.elixir-czech.cz/sparql/endpoint/chembl> {
        ?COMPOUND sachem:substructureSearch [
            sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
      }

    ?ACTIVITY rdf:type chembl:Activity;
      chembl:hasMolecule ?COMPOUND;
      chembl:hasAssay ?ASSAY.
    ?ASSAY chembl:hasTarget ?TARGET.
    ?TARGET chembl:hasTargetComponent ?COMPONENT.
    ?COMPONENT chembl:targetCmptXref ?UNIPROT.
    ?UNIPROT rdf:type chembl:UniprotRef.
  }

  ?ORGANISM uniprot:scientificName ?ORGANISM_NAME.
}
Limit 10


---------------------------------------------------
endpoint:
https://sparql.uniprot.org/sparql


query:
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX sachem: <http://bioinfo.uochb.cas.cz/rdf/v1.0/sachem#>
PREFIX up:<http://purl.uniprot.org/core/>
PREFIX rh:<http://rdf.rhea-db.org/>
PREFIX ch:<http://purl.obolibrary.org/obo/>
PREFIX taxon:<http://purl.uniprot.org/taxonomy/>
PREFIX keywords:<http://purl.uniprot.org/keywords/>

SELECT * WHERE {
  SERVICE <https://sparql.rhea-db.org/sparql>
  {
    SERVICE <https://idsm.elixir-czech.cz/sparql/endpoint/chebi> {
      ?CHEBI sachem:substructureSearch [
          sachem:query "C1C2(C3(CCC4(C(C3(CC=C2CC(C1)O))(CCC4(C(C)CCCC(C)C)))C))C" ].
    }

    ?RHEA_REACTION rdfs:subClassOf rh:Reaction .
    ?RHEA_REACTION rh:status rh:Approved .
    ?RHEA_REACTION rh:side / rh:contains / rh:compound / rh:chebi ?CHEBI .
    ?CHEBI up:name ?CHEBI_UNIPROT_NAME .
  }
}
---------------------------

endpoint: https://sparql.uniprot.org

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX sachem: <http://bioinfo.uochb.cas.cz/rdf/v1.0/sachem#>
PREFIX endpoint: <https://idsm.elixir-czech.cz/sparql/endpoint/>

SELECT ?COMPOUND ?UNIPROT ?ORGANISM_NAME WHERE
{

  {
    SELECT ?UNIPROT ?ORGANISM WHERE
    {
      ?UNIPROT uniprot:organism ?ORGANISM.
    } LIMIT 2
  }

    SERVICE endpoint:idsm {
      SERVICE endpoint:chembl {
        SERVICE endpoint:chembl {
          ?COMPOUND sachem:substructureSearch [
              sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
        }

        ?COMPOUND sachem:substructureSearch [
            sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
      }

    ?ACTIVITY rdf:type chembl:Activity;
      chembl:hasMolecule ?COMPOUND;
      chembl:hasAssay ?ASSAY.

    SERVICE endpoint:idsm {
      SERVICE endpoint:chembl {
        ?COMPOUND_1 sachem:substructureSearch [
            sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
      }

      ?ACTIVITY rdf:type chembl:Activity;
                chembl:hasMolecule ?COMPOUND;
                chembl:hasAssay ?ASSAY.
      ?ASSAY chembl:hasTarget ?TARGET.
      ?TARGET chembl:hasTargetComponent ?COMPONENT.
      ?COMPONENT chembl:targetCmptXref ?UNIPROT.
      ?UNIPROT rdf:type chembl:UniprotRef.
    }

    ?UNIPROT rdf:type chembl:UniprotRef.
  }

  ?UNIPROT uniprot:organism ?COMPOUND_1.
  ?ORGANISM uniprot:scientificName ?ORGANISM_NAME.
}
LIMIT 10

---------------------------------------
endpoint: https://sparql.uniprot.org

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX uniprot: <http://purl.uniprot.org/core/>
PREFIX sachem: <http://bioinfo.uochb.cas.cz/rdf/v1.0/sachem#>
PREFIX endpoint: <https://idsm.elixir-czech.cz/sparql/endpoint/>

SELECT ?COMPOUND ?UNIPROT ?ORGANISM_NAME WHERE
{
    {
      SELECT ?UNIPROT ?ORGANISM WHERE
      {
        ?UNIPROT uniprot:organism ?ORGANISM.
      } LIMIT 5
    }

    SERVICE endpoint:idsm {
      SERVICE endpoint:chembl {
        SERVICE endpoint:chembl {
          ?COMPOUND sachem:substructureSearch [
              sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
        }
        ?COMPOUND sachem:substructureSearch [
            sachem:query "CC(=O)Oc1ccccc1C(O)=O" ]
      }

    ?ACTIVITY rdf:type chembl:Activity;
      chembl:hasMolecule ?COMPOUND;
      chembl:hasAssay ?ASSAY.
    ?ASSAY chembl:hasTarget ?TARGET.
    ?TARGET chembl:hasTargetComponent ?COMPONENT.
    ?COMPONENT chembl:targetCmptXref ?UNIPROT.
    ?UNIPROT rdf:type chembl:UniprotRef.
  }

  ?UNIPROT uniprot:organism ?ORGANISM.
  ?ORGANISM uniprot:scientificName ?ORGANISM_NAME.
}